BaseUrl= "https://blog.aria.ai/"
LanguageCode= "en-EN"
Title= "Aria"
paginate = 10
DisqusShortname = "ariafallah"
Copyright = "All rights reserved - 2016"
canonifyurls = false

[params]
  author = "Aria Fallah"
  authorlocation = "127.0.0.1"
  authorwebsite = "https://aria.ai"
  cover = "images/cover.png"
  description = "On a scale of 1 to my blog, this is my blog"
  googleAnalyticsUserID = "UA-79031036-1"
  logo = "images/logo.svg"
